"""
ApnaSamaj – Base SQLAlchemy Model

Every table in the system inherits from BaseModel which provides:
  • UUID primary key (database-generated)
  • tenant_id foreign key for row-level multi-tenant isolation
  • Soft delete via is_deleted + deleted_at
  • Audit columns: created_at, updated_at, created_by, updated_by

Design decisions:
  • UUID v4 generated by the database (server_default) for portability.
  • tenant_id is NOT nullable – every row belongs to a tenant. Only the
    'tenants' table itself and global lookup tables omit it.
  • Indexes on tenant_id for fast filtered queries.
  • __tablename__ auto-generated from class name (snake_case).
"""

from __future__ import annotations

import re
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column


class Base(DeclarativeBase):
    """Raw declarative base – used by Alembic and for tables that don't
    need tenant isolation (e.g. the tenants table itself)."""

    pass


class BaseModel(Base):
    """
    Abstract base for ALL tenant-scoped tables.

    Provides UUID PK, tenant_id FK, soft-delete, and audit columns.
    """

    __abstract__ = True

    # ── Primary Key ──────────────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )

    # ── Multi-Tenant ─────────────────────────────────────────────────────
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Soft Delete ──────────────────────────────────────────────────────
    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default=text("false"),
        nullable=False,
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    # ── Audit Columns ────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        onupdate=text("now()"),
        nullable=False,
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    # ── Auto table name ─────────────────────────────────────────────────
    @declared_attr.directive
    @classmethod
    def __tablename__(cls) -> str:
        """Convert CamelCase class name → snake_case table name."""
        name = re.sub(r"(?<!^)(?=[A-Z])", "_", cls.__name__).lower()
        return name

    @declared_attr.directive
    @classmethod
    def __table_args__(cls) -> tuple:
        """Default index on tenant_id + is_deleted for filtered queries."""
        return (
            Index(
                f"ix_{cls.__tablename__}_tenant_active",
                "tenant_id",
                "is_deleted",
            ),
        )


class GlobalBaseModel(Base):
    """
    Abstract base for tables that do NOT have tenant isolation.
    Examples: tenants, global settings, super-admin users.
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )

    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        server_default=text("false"),
        nullable=False,
    )
    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        onupdate=text("now()"),
        nullable=False,
    )
    created_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )
    updated_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    @declared_attr.directive
    @classmethod
    def __tablename__(cls) -> str:
        name = re.sub(r"(?<!^)(?=[A-Z])", "_", cls.__name__).lower()
        return name
